name       : git-extras
version    : 4.6.0
release    : 2
source     :
    - https://github.com/tj/git-extras/archive/4.6.0.tar.gz : e3baa3a54cb3d8f2e09409e9dec22c76c0e4802e44e108b6cc0b4b0245e4e5ca
license    : MIT
component  : programming.tools
summary    : Little git extras.
description: |
    Little git extras.
builddeps  :
    - git
rundeps    :
    - git
install    : |
    %make_install PREFIX=/usr
