name       : git-extras
version    : 6.5.0
release    : 9
source     :
    - https://github.com/tj/git-extras/archive/refs/tags/6.5.0.tar.gz : eace7a0659749c72abf1cee68c03ea0a77715870d5e321c729e4a231ee359b61
license    : MIT
component  : programming.tools
summary    : Little git extras.
description: |
    Little git extras.
builddeps  :
    - git
rundeps    :
    - git
install    : |
    %make_install PREFIX=/usr

    install -Dm0644 etc/git-extras.fish $installdir/usr/share/fish/vendor_completions.d/git-extras.fish
