name       : git-extras
version    : 4.0.0
release    : 1
source     :
    - https://github.com/tj/git-extras/archive/4.0.0.tar.gz : 4adaadc1f22f3240ae9607963ede29a5c010ae14b877b90c27d17d6b0c06f430
license    : MIT
summary    : Little git extras.
description: |
    Little git extras.
rundeps:
    - git
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
