name       : git-extras
version    : 6.1.0
release    : 5
source     :
    - https://github.com/tj/git-extras/archive/6.1.0.tar.gz : 7be0b15ee803d76d2c2e8036f5d9db6677f2232bb8d2c4976691ff7ae026a22f
license    : MIT
component  : programming.tools
summary    : Little git extras.
description: |
    Little git extras.
builddeps  :
    - git
rundeps    :
    - git
install    : |
    %make_install PREFIX=/usr

    install -Dm0644 etc/git-extras.fish $installdir/usr/share/fish/vendor_completions.d/git-extras.fish
