name       : git-extras
version    : 6.3.0
release    : 7
source     :
    - https://github.com/tj/git-extras/archive/refs/tags/6.3.0.tar.gz : 8a218a0c8e10036d5ba14f26b70f994b0d11166b02ef3fed71c593cef026ec3d
license    : MIT
component  : programming.tools
summary    : Little git extras.
description: |
    Little git extras.
builddeps  :
    - git
rundeps    :
    - git
install    : |
    %make_install PREFIX=/usr

    install -Dm0644 etc/git-extras.fish $installdir/usr/share/fish/vendor_completions.d/git-extras.fish
