name       : git-extras
version    : 7.0.0
release    : 10
source     :
    - https://github.com/tj/git-extras/archive/refs/tags/7.0.0.tar.gz : 3adcbc247d6cb78dc58cace22e9ad789cd6f5061522516660dfb59cc6ec08def
license    : MIT
component  : programming.tools
summary    : Little git extras.
description: |
    Little git extras.
builddeps  :
    - git
rundeps    :
    - git
install    : |
    %make_install PREFIX=/usr

    install -Dm0644 etc/git-extras.fish $installdir/usr/share/fish/vendor_completions.d/git-extras.fish
